/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import {useGLTF} from '@react-three/drei';
import {ThreeCanvas} from '@remotion/three';
import {useVideoConfig} from 'remotion';
import {Casette} from './Casette';
import {Stage} from './Stage';

export const Scene = () => {
	const {width, height} = useVideoConfig();
	return (
		<ThreeCanvas
			shadows
			width={width}
			height={height}
			dpr={[1, 2]}
			camera={{fov: 70}}
			style={{
				height,
				width,
			}}
		>
			<Stage preset="rembrandt" intensity={1} environment="city">
				<Casette />
			</Stage>
		</ThreeCanvas>
	);
};

useGLTF.preload(
	'https://jonnyburger.s3.eu-central-1.amazonaws.com/casette-full-labeled-v4.glb'
);
